DROP TABLE IF EXISTS `PREFIX_ntbr_ftp`;
DROP TABLE IF EXISTS `PREFIX_ntbr_dropbox`;
DROP TABLE IF EXISTS `PREFIX_ntbr_owncloud`;
DROP TABLE IF EXISTS `PREFIX_ntbr_webdav`;
DROP TABLE IF EXISTS `PREFIX_ntbr_googledrive`;
DROP TABLE IF EXISTS `PREFIX_ntbr_onedrive`;
DROP TABLE IF EXISTS `PREFIX_ntbr_hubic`;
DROP TABLE IF EXISTS `PREFIX_ntbr_aws`;